# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- main

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build image
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: DotNetCoreCLI@2
      displayName: Restore project deps
      inputs:
        command: 'restore'
        projects: $(solution)
        feedsToUse: 'select'
    - task: DotNetCoreCLI@2
      displayName: Build the solution
      inputs:
        command: 'build'
        projects: $(solution)
    - task: DotNetCoreCLI@2
      displayName: Test
      inputs:
        command: 'test'
        projects: '**/Jean-Monegro-P1/FinalCarLot/RRTests/*.csproj'
    - task: Docker@2
      displayName: Build an image
      inputs:
        command: build
        dockerfile: '$(Build.SourcesDirectory)/FinalCarLot/dockerfile'
        tags: |
          $(tag)
